version: '3.8'
services:
  database:
    image: postgres:16-alpine
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - target: 5432
        host_ip: 127.0.0.1
        published: ${POSTGRES_PORT}
        protocol: tcp
        mode: host
    volumes:
      - ./db-data:/var/lib/postgresql/data
